server:
    port: 8085
spring:
    datasource:
        username: root
        password: zjtzjy137381
        url: jdbc:mysql://localhost:3306/taotao?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    redis:
        password: 123456
        host: 152.136.119.210
        port: 7001
        cluster:
            nodes: 152.136.119.210:7001,152.136.119.210:7002,152.136.119.210:7003,152.136.119.210:7004,152.136.119.210:7005,152.136.119.210:7006
        jedis:
            pool:
                max-active: 10
                max-idle: 2
                min-idle: 1
#        static-path-pattern: /static/**
#        resources:
#            static-locations: classpath:/static/
#    mvc:
##        date-format: yyyy-MM-dd HH:mm:ss
#        static-path-pattern: /static/**
#        resources:
#            static-locations: classpath:/static/

mybatis:
    mapper-locations: classpath:/mappers/*.xml


